{% set name = "wagtail-sb-admin-interface" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail_sb_admin_interface-{{ version }}.tar.gz
  sha256: dc847e223eebe177711e1dab700714fcd1966df26818f46eb88ec455be1a12ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - django <5.0
    - django-colorfield <1.0.0
    - wagtail <6.0

test:
  imports:
    - wagtail_sb_admin_interface
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/softbutterfly/open-source/wagtail-sb-admin-interface
  summary: Customize the Wagtail admin interface from the admin itself.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
